format = """
[](#1e2030)\
$os\
$username\
[](bg:#363a4f fg:#1e2030)\
$directory\
[](fg:#363a4f bg:#8aadf4)\
$git_branch\
$git_status\
[](fg:#8aadf4 bg:#24273a)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#24273a bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#24273a)\
$time\
[ ](fg:#24273a)\
$conda\
$cmd_duration
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#1e2030"
style_root = "bg:#1e2030"
format = '[$user ]($style)'
disabled = false

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'
# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true# Disabled by default

[directory]
style = "bg:#363a4f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = ""
style = "fg:#a6da95"
format = '[$symbol $environment]($style) '

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#24273a bg:#8aadf4"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#24273a bg:#8aadf4"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "🦀"
style = "fg:#f5a97f bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#24273a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#24273a"
format = '[$symbol ($version) ${conda}]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#24273a"
format = '[ $time ]($style)'
